### ISSUE TITLE
Ambiguity in Training Data - Prioritization guideance

### ISSUE THREAD

**Issue by andrewrfreed** [watson-developer-cloud/assistant-skill-analysis#10]
Cell 1.5 - Ambiguity in Training Data - is a very useful report.

Can we quantify or prioritize what overlap should be addressed - perhaps an "overlap score" - showing the worst overlaps or the ones most impactful to improving the training.

Ideally the tool suggests what I do next, this would be informed by:
Work on ambiguity between my most confused intents first (leveraging earlier chi-square or a k-folds analysis)
Work on the most significant overlaps, ie which ones give me the most bang for the buck.

**Comment by haodeqi** [comment]
@andrewrfreed Hi, Andrew. In our current design, the output is sorted by the similarity score at example-pairs level. We aim to tackle this problem here at a more microscopic level and if the user is seeing a pattern between intents, we direct them to the **Watson  Assistant Intent Conflict Resolution**.

I agree with your point for the time-to-reward for customers. Therefore, We ask the user to go through the sort list starting with the examples with the highest similarity scores. However, the user will still need to go through the list because higher similarity score does not guarantee ambiguity at the semantic level.

**Comment by haodeqi** [comment]
issue closed and we will revisit if necessary.
